//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCVK.HCVKAService.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MultiLang {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MultiLang() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HCVKAService.Resources.MultiLang", typeof(MultiLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HCVKA_SERVICE_MSG_0001 {
            get {
                return ResourceManager.GetString("HCVKA_SERVICE_MSG_0001", resourceCulture);
            }
        }
        
        internal static string HCVKA_SERVICE_MSG_0002 {
            get {
                return ResourceManager.GetString("HCVKA_SERVICE_MSG_0002", resourceCulture);
            }
        }
        
        internal static string HCVKA_SERVICE_MSG_0003 {
            get {
                return ResourceManager.GetString("HCVKA_SERVICE_MSG_0003", resourceCulture);
            }
        }
        
        internal static string HCVKA_SERVICE_MSG_0004 {
            get {
                return ResourceManager.GetString("HCVKA_SERVICE_MSG_0004", resourceCulture);
            }
        }
        
        internal static string HCVKA_SERVICE_MSG_0005 {
            get {
                return ResourceManager.GetString("HCVKA_SERVICE_MSG_0005", resourceCulture);
            }
        }
        
        internal static string HCVKA_SERVICE_MSG_0006 {
            get {
                return ResourceManager.GetString("HCVKA_SERVICE_MSG_0006", resourceCulture);
            }
        }
        
        internal static string HCVKA_SERVICE_MSG_0007 {
            get {
                return ResourceManager.GetString("HCVKA_SERVICE_MSG_0007", resourceCulture);
            }
        }
        
        internal static string HCVKA_SERVICE_MSG_0008 {
            get {
                return ResourceManager.GetString("HCVKA_SERVICE_MSG_0008", resourceCulture);
            }
        }
        
        internal static string HCVKA_SERVICE_MSG_0009 {
            get {
                return ResourceManager.GetString("HCVKA_SERVICE_MSG_0009", resourceCulture);
            }
        }
    }
}
