
// This file has been generated by the GUI designer. Do not modify.
namespace client
{
	public partial class serverItemWidget
	{
		private global::Gtk.EventBox eventbox;

		private global::Gtk.VBox vbox10;

		private global::Gtk.Fixed fixedDefault;

		private global::Gtk.Image imageServer;

		private global::Gtk.Label labelServerIP;

		private global::Gtk.EventBox eventboxPort;

		private global::Gtk.Label labelServerPort;

		private global::Gtk.Image imageArrow;

		private global::Gtk.Label labelServerName;

		private global::Gtk.Fixed fixedDetail;

		private global::Gtk.Label labelConnectedTime;

		private global::Gtk.Label labelServerStatus;

		private global::Gtk.Label labelServerState;

		private global::Gtk.Button btnRemove;

		private global::Gtk.Button btnEdit;

		private global::Gtk.Button btnLogIn;

		private global::Gtk.Label labelConnectedTimeValue;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget client.serverItemWidget
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 200;
			this.Name = "client.serverItemWidget";
			// Container child client.serverItemWidget.Gtk.Container+ContainerChild
			this.eventbox = new global::Gtk.EventBox();
			this.eventbox.Name = "eventbox";
			// Container child eventbox.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.fixedDefault = new global::Gtk.Fixed();
			this.fixedDefault.WidthRequest = 256;
			this.fixedDefault.HeightRequest = 70;
			this.fixedDefault.Name = "fixedDefault";
			this.fixedDefault.HasWindow = false;
			// Container child fixedDefault.Gtk.Fixed+FixedChild
			this.imageServer = new global::Gtk.Image();
			this.imageServer.Name = "imageServer";
			this.imageServer.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("client.Resources.icon_broker_enable.png");
			this.fixedDefault.Add(this.imageServer);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixedDefault[this.imageServer]));
			w1.X = 12;
			w1.Y = 30;
			// Container child fixedDefault.Gtk.Fixed+FixedChild
			this.labelServerIP = new global::Gtk.Label();
			this.labelServerIP.WidthRequest = 100;
			this.labelServerIP.Name = "labelServerIP";
			this.labelServerIP.Xalign = 0F;
			this.labelServerIP.LabelProp = global::Mono.Unix.Catalog.GetString("label3");
			this.fixedDefault.Add(this.labelServerIP);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixedDefault[this.labelServerIP]));
			w2.X = 45;
			w2.Y = 40;
			// Container child fixedDefault.Gtk.Fixed+FixedChild
			this.eventboxPort = new global::Gtk.EventBox();
			this.eventboxPort.Name = "eventboxPort";
			// Container child eventboxPort.Gtk.Container+ContainerChild
			this.labelServerPort = new global::Gtk.Label();
			this.labelServerPort.WidthRequest = 50;
			this.labelServerPort.Name = "labelServerPort";
			this.labelServerPort.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.eventboxPort.Add(this.labelServerPort);
			this.fixedDefault.Add(this.eventboxPort);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixedDefault[this.eventboxPort]));
			w4.X = 153;
			w4.Y = 41;
			// Container child fixedDefault.Gtk.Fixed+FixedChild
			this.imageArrow = new global::Gtk.Image();
			this.imageArrow.Name = "imageArrow";
			this.imageArrow.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("client.Resources.server_arrow_enable.png");
			this.fixedDefault.Add(this.imageArrow);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixedDefault[this.imageArrow]));
			w5.X = 227;
			w5.Y = 35;
			// Container child fixedDefault.Gtk.Fixed+FixedChild
			this.labelServerName = new global::Gtk.Label();
			this.labelServerName.WidthRequest = 160;
			this.labelServerName.Name = "labelServerName";
			this.labelServerName.Xalign = 0F;
			this.labelServerName.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\'15000\'>big text</span>");
			this.labelServerName.UseMarkup = true;
			this.fixedDefault.Add(this.labelServerName);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixedDefault[this.labelServerName]));
			w6.X = 43;
			w6.Y = 16;
			this.vbox10.Add(this.fixedDefault);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.fixedDefault]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.fixedDetail = new global::Gtk.Fixed();
			this.fixedDetail.HeightRequest = 75;
			this.fixedDetail.Name = "fixedDetail";
			this.fixedDetail.HasWindow = false;
			// Container child fixedDetail.Gtk.Fixed+FixedChild
			this.labelConnectedTime = new global::Gtk.Label();
			this.labelConnectedTime.WidthRequest = 120;
			this.labelConnectedTime.HeightRequest = 14;
			this.labelConnectedTime.Name = "labelConnectedTime";
			this.labelConnectedTime.Xalign = 0F;
			this.labelConnectedTime.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\'9000\'>Last Access Time</span>");
			this.labelConnectedTime.UseMarkup = true;
			this.fixedDetail.Add(this.labelConnectedTime);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixedDetail[this.labelConnectedTime]));
			w8.Y = 5;
			// Container child fixedDetail.Gtk.Fixed+FixedChild
			this.labelServerStatus = new global::Gtk.Label();
			this.labelServerStatus.WidthRequest = 100;
			this.labelServerStatus.HeightRequest = 14;
			this.labelServerStatus.Name = "labelServerStatus";
			this.labelServerStatus.Xalign = 0F;
			this.labelServerStatus.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\'9000\'>Server State</span>");
			this.labelServerStatus.UseMarkup = true;
			this.fixedDetail.Add(this.labelServerStatus);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixedDetail[this.labelServerStatus]));
			w9.Y = 22;
			// Container child fixedDetail.Gtk.Fixed+FixedChild
			this.labelServerState = new global::Gtk.Label();
			this.labelServerState.WidthRequest = 150;
			this.labelServerState.Name = "labelServerState";
			this.labelServerState.Xalign = 0F;
			this.labelServerState.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\'9000\'>label</span>");
			this.labelServerState.UseMarkup = true;
			this.fixedDetail.Add(this.labelServerState);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixedDetail[this.labelServerState]));
			w10.X = 115;
			w10.Y = 22;
			// Container child fixedDetail.Gtk.Fixed+FixedChild
			this.btnRemove = new global::Gtk.Button();
			this.btnRemove.WidthRequest = 85;
			this.btnRemove.HeightRequest = 36;
			this.btnRemove.CanFocus = true;
			this.btnRemove.Name = "btnRemove";
			this.btnRemove.Label = global::Mono.Unix.Catalog.GetString("REMOVE");
			this.fixedDetail.Add(this.btnRemove);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixedDetail[this.btnRemove]));
			w11.Y = 40;
			// Container child fixedDetail.Gtk.Fixed+FixedChild
			this.btnEdit = new global::Gtk.Button();
			this.btnEdit.WidthRequest = 85;
			this.btnEdit.HeightRequest = 36;
			this.btnEdit.CanFocus = true;
			this.btnEdit.Name = "btnEdit";
			this.btnEdit.Label = global::Mono.Unix.Catalog.GetString("EDIT");
			this.fixedDetail.Add(this.btnEdit);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixedDetail[this.btnEdit]));
			w12.X = 84;
			w12.Y = 40;
			// Container child fixedDetail.Gtk.Fixed+FixedChild
			this.btnLogIn = new global::Gtk.Button();
			this.btnLogIn.WidthRequest = 85;
			this.btnLogIn.HeightRequest = 36;
			this.btnLogIn.CanFocus = true;
			this.btnLogIn.Name = "btnLogIn";
			this.btnLogIn.Label = global::Mono.Unix.Catalog.GetString("LOGIN");
			this.fixedDetail.Add(this.btnLogIn);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixedDetail[this.btnLogIn]));
			w13.X = 169;
			w13.Y = 40;
			// Container child fixedDetail.Gtk.Fixed+FixedChild
			this.labelConnectedTimeValue = new global::Gtk.Label();
			this.labelConnectedTimeValue.WidthRequest = 150;
			this.labelConnectedTimeValue.Name = "labelConnectedTimeValue";
			this.labelConnectedTimeValue.Xalign = 0F;
			this.labelConnectedTimeValue.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\'9000\'>label</span>");
			this.labelConnectedTimeValue.UseMarkup = true;
			this.fixedDetail.Add(this.labelConnectedTimeValue);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixedDetail[this.labelConnectedTimeValue]));
			w14.X = 115;
			w14.Y = 5;
			this.vbox10.Add(this.fixedDetail);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.fixedDetail]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.eventbox.Add(this.vbox10);
			this.Add(this.eventbox);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.eventbox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.OnEventboxButtonPressEvent);
			this.eventbox.EnterNotifyEvent += new global::Gtk.EnterNotifyEventHandler(this.OnEventboxEnterNotifyEvent);
			this.eventbox.LeaveNotifyEvent += new global::Gtk.LeaveNotifyEventHandler(this.OnEventboxLeaveNotifyEvent);
			this.btnRemove.Clicked += new global::System.EventHandler(this.OnBtnRemoveClicked);
			this.btnEdit.Clicked += new global::System.EventHandler(this.OnBtnEditClicked);
			this.btnLogIn.Clicked += new global::System.EventHandler(this.OnBtnLogInClicked);
		}
	}
}
