
// This file has been generated by the GUI designer. Do not modify.
namespace client
{
	public partial class desktoplistWidget
	{
		private global::Gtk.VBox vbox209;

		private global::Gtk.EventBox eventboxDesktoplist;

		private global::Gtk.VBox vbox509;

		private global::Gtk.ScrolledWindow scrollDesktoplist9;

		private global::Gtk.VBox vboxDesktoplist;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget client.desktoplistWidget
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 256;
			this.HeightRequest = 377;
			this.Name = "client.desktoplistWidget";
			// Container child client.desktoplistWidget.Gtk.Container+ContainerChild
			this.vbox209 = new global::Gtk.VBox();
			this.vbox209.Name = "vbox209";
			this.vbox209.Spacing = 6;
			// Container child vbox209.Gtk.Box+BoxChild
			this.eventboxDesktoplist = new global::Gtk.EventBox();
			this.eventboxDesktoplist.Name = "eventboxDesktoplist";
			// Container child eventboxDesktoplist.Gtk.Container+ContainerChild
			this.vbox509 = new global::Gtk.VBox();
			this.vbox509.Name = "vbox509";
			this.vbox509.Spacing = 6;
			// Container child vbox509.Gtk.Box+BoxChild
			this.scrollDesktoplist9 = new global::Gtk.ScrolledWindow();
			this.scrollDesktoplist9.CanFocus = true;
			this.scrollDesktoplist9.Name = "scrollDesktoplist9";
			this.scrollDesktoplist9.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrollDesktoplist9.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vboxDesktoplist = new global::Gtk.VBox();
			this.vboxDesktoplist.Name = "vboxDesktoplist";
			this.vboxDesktoplist.Spacing = 6;
			w1.Add(this.vboxDesktoplist);
			this.scrollDesktoplist9.Add(w1);
			this.vbox509.Add(this.scrollDesktoplist9);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox509[this.scrollDesktoplist9]));
			w4.Position = 0;
			this.eventboxDesktoplist.Add(this.vbox509);
			this.vbox209.Add(this.eventboxDesktoplist);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox209[this.eventboxDesktoplist]));
			w6.Position = 0;
			this.Add(this.vbox209);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
