
// This file has been generated by the GUI designer. Do not modify.
namespace client
{
	public partial class bookmarkPageWidget
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.VBox vboxBookmark;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget client.bookmarkPageWidget
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 512;
			this.HeightRequest = 377;
			this.Name = "client.bookmarkPageWidget";
			// Container child client.bookmarkPageWidget.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vboxBookmark = new global::Gtk.VBox();
			this.vboxBookmark.Name = "vboxBookmark";
			this.vboxBookmark.Spacing = 6;
			w1.Add(this.vboxBookmark);
			this.scrolledwindow1.Add(w1);
			this.Add(this.scrolledwindow1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
