
// This file has been generated by the GUI designer. Do not modify.
namespace client
{
	public partial class settingPageWidget
	{
		private global::Gtk.Notebook notebook1;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.Label labelServerName;

		private global::Gtk.Label labelDesktopName;

		private global::Gtk.ComboBox cbxLang;

		private global::Gtk.ComboBox cbxNetwork;

		private global::Gtk.RadioButton radioEnableBookmarkOn;

		private global::Gtk.RadioButton radioEnableBookmarkOff;

		private global::Gtk.RadioButton radioAutoStartOn;

		private global::Gtk.RadioButton radioAutoStartOff;

		private global::Gtk.Entry tbxServerName;

		private global::Gtk.Entry tbxDesktopName;

		private global::Gtk.Button ButtonNetworkRefresh;

		private global::Gtk.CheckButton chkAutoClientIP;

		private global::Gtk.RadioButton radioAutoReconnectOn;

		private global::Gtk.RadioButton radioAutoReconnectOff;

		private global::Gtk.Label label19;

		private global::Gtk.Label label1;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Label label10;

		private global::Gtk.Label label11;

		private global::Gtk.Label label12;

		private global::Gtk.Label label13;

		private global::Gtk.Label label14;

		private global::Gtk.RadioButton radioDualOn;

		private global::Gtk.RadioButton radioDualOff;

		private global::Gtk.RadioButton radioAudioOn;

		private global::Gtk.RadioButton radioAudioOff;

		private global::Gtk.ComboBox cbxProtocol;

		private global::Gtk.ComboBox cbxResolution;

		private global::Gtk.ComboBox cbxSpeed;

		private global::Gtk.Label label16;

		private global::Gtk.ComboBox cbxColorDepth;

		private global::Gtk.CheckButton chkDynamicResolutionUpdate;

		private global::Gtk.Label label9;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.Label label7;

		private global::Gtk.Label label8;

		private global::Gtk.Label label15;

		private global::Gtk.CheckButton chkClipboard;

		private global::Gtk.CheckButton chkLocalPrinter;

		private global::Gtk.CheckButton chkLocalDriver;

		private global::Gtk.CheckButton chkLocalDevice;

		private global::Gtk.CheckButton chkLocalPort;

		private global::Gtk.CheckButton chkSmartCard;

		private global::Gtk.CheckButton chkBitmapCaching;

		private global::Gtk.CheckButton chkMicrophone;

		private global::Gtk.CheckButton chkVideoCaptureDevice;

		private global::Gtk.CheckButton chkUseRDPEcam;

		private global::Gtk.Label label17;

		private global::Gtk.CheckButton chkUseH264;

		private global::Gtk.Label label2;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.Label label18;

		private global::Gtk.CheckButton chkExtRDPViewer;

		private global::Gtk.Label label20;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget client.settingPageWidget
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 520;
			this.HeightRequest = 377;
			this.Name = "client.settingPageWidget";
			// Container child client.settingPageWidget.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Language");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w1.X = 65;
			w1.Y = 56;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Network");
			this.fixed1.Add(this.label4);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
			w2.X = 65;
			w2.Y = 96;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Enable Bookmark");
			this.fixed1.Add(this.label5);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
			w3.X = 65;
			w3.Y = 176;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Auto Start");
			this.fixed1.Add(this.label6);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label6]));
			w4.X = 65;
			w4.Y = 216;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelServerName = new global::Gtk.Label();
			this.labelServerName.Name = "labelServerName";
			this.labelServerName.LabelProp = global::Mono.Unix.Catalog.GetString("Server Name");
			this.fixed1.Add(this.labelServerName);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.labelServerName]));
			w5.X = 80;
			w5.Y = 256;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelDesktopName = new global::Gtk.Label();
			this.labelDesktopName.Name = "labelDesktopName";
			this.labelDesktopName.LabelProp = global::Mono.Unix.Catalog.GetString("Desktop Name");
			this.fixed1.Add(this.labelDesktopName);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.labelDesktopName]));
			w6.X = 80;
			w6.Y = 296;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.cbxLang = global::Gtk.ComboBox.NewText();
			this.cbxLang.AppendText(global::Mono.Unix.Catalog.GetString("ko-KR"));
			this.cbxLang.AppendText(global::Mono.Unix.Catalog.GetString("en-US"));
			this.cbxLang.Name = "cbxLang";
			this.cbxLang.Active = 0;
			this.fixed1.Add(this.cbxLang);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.cbxLang]));
			w7.X = 234;
			w7.Y = 51;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.cbxNetwork = global::Gtk.ComboBox.NewText();
			this.cbxNetwork.Name = "cbxNetwork";
			this.fixed1.Add(this.cbxNetwork);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.cbxNetwork]));
			w8.X = 234;
			w8.Y = 91;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.radioEnableBookmarkOn = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("On"));
			this.radioEnableBookmarkOn.CanFocus = true;
			this.radioEnableBookmarkOn.Name = "radioEnableBookmarkOn";
			this.radioEnableBookmarkOn.DrawIndicator = true;
			this.radioEnableBookmarkOn.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.fixed1.Add(this.radioEnableBookmarkOn);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.radioEnableBookmarkOn]));
			w9.X = 234;
			w9.Y = 176;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.radioEnableBookmarkOff = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Off"));
			this.radioEnableBookmarkOff.CanFocus = true;
			this.radioEnableBookmarkOff.Name = "radioEnableBookmarkOff";
			this.radioEnableBookmarkOff.DrawIndicator = true;
			this.radioEnableBookmarkOff.Group = this.radioEnableBookmarkOn.Group;
			this.fixed1.Add(this.radioEnableBookmarkOff);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.radioEnableBookmarkOff]));
			w10.X = 320;
			w10.Y = 176;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.radioAutoStartOn = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("On"));
			this.radioAutoStartOn.CanFocus = true;
			this.radioAutoStartOn.Name = "radioAutoStartOn";
			this.radioAutoStartOn.DrawIndicator = true;
			this.radioAutoStartOn.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.fixed1.Add(this.radioAutoStartOn);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.radioAutoStartOn]));
			w11.X = 234;
			w11.Y = 216;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.radioAutoStartOff = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Off"));
			this.radioAutoStartOff.CanFocus = true;
			this.radioAutoStartOff.Name = "radioAutoStartOff";
			this.radioAutoStartOff.DrawIndicator = true;
			this.radioAutoStartOff.Group = this.radioAutoStartOn.Group;
			this.fixed1.Add(this.radioAutoStartOff);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.radioAutoStartOff]));
			w12.X = 320;
			w12.Y = 216;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbxServerName = new global::Gtk.Entry();
			this.tbxServerName.Sensitive = false;
			this.tbxServerName.CanFocus = true;
			this.tbxServerName.Name = "tbxServerName";
			this.tbxServerName.IsEditable = false;
			this.tbxServerName.InvisibleChar = '•';
			this.fixed1.Add(this.tbxServerName);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tbxServerName]));
			w13.X = 234;
			w13.Y = 256;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbxDesktopName = new global::Gtk.Entry();
			this.tbxDesktopName.Sensitive = false;
			this.tbxDesktopName.CanFocus = true;
			this.tbxDesktopName.Name = "tbxDesktopName";
			this.tbxDesktopName.IsEditable = false;
			this.tbxDesktopName.InvisibleChar = '•';
			this.fixed1.Add(this.tbxDesktopName);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tbxDesktopName]));
			w14.X = 234;
			w14.Y = 296;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.ButtonNetworkRefresh = new global::Gtk.Button();
			this.ButtonNetworkRefresh.CanFocus = true;
			this.ButtonNetworkRefresh.Name = "ButtonNetworkRefresh";
			this.ButtonNetworkRefresh.UseUnderline = true;
			this.ButtonNetworkRefresh.Label = global::Mono.Unix.Catalog.GetString("Refresh");
			this.fixed1.Add(this.ButtonNetworkRefresh);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ButtonNetworkRefresh]));
			w15.X = 167;
			w15.Y = 92;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.chkAutoClientIP = new global::Gtk.CheckButton();
			this.chkAutoClientIP.CanFocus = true;
			this.chkAutoClientIP.Name = "chkAutoClientIP";
			this.chkAutoClientIP.Label = global::Mono.Unix.Catalog.GetString("Auto IP");
			this.chkAutoClientIP.DrawIndicator = true;
			this.chkAutoClientIP.UseUnderline = true;
			this.fixed1.Add(this.chkAutoClientIP);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkAutoClientIP]));
			w16.X = 160;
			w16.Y = 95;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.radioAutoReconnectOn = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("On"));
			this.radioAutoReconnectOn.CanFocus = true;
			this.radioAutoReconnectOn.Name = "radioAutoReconnectOn";
			this.radioAutoReconnectOn.DrawIndicator = true;
			this.radioAutoReconnectOn.UseUnderline = true;
			this.radioAutoReconnectOn.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.fixed1.Add(this.radioAutoReconnectOn);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.radioAutoReconnectOn]));
			w17.X = 234;
			w17.Y = 136;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.radioAutoReconnectOff = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Off"));
			this.radioAutoReconnectOff.CanFocus = true;
			this.radioAutoReconnectOff.Name = "radioAutoReconnectOff";
			this.radioAutoReconnectOff.DrawIndicator = true;
			this.radioAutoReconnectOff.UseUnderline = true;
			this.radioAutoReconnectOff.Group = this.radioAutoReconnectOn.Group;
			this.fixed1.Add(this.radioAutoReconnectOff);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.radioAutoReconnectOff]));
			w18.X = 320;
			w18.Y = 136;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Auto Reconnect");
			this.fixed1.Add(this.label19);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label19]));
			w19.X = 65;
			w19.Y = 136;
			this.notebook1.Add(this.fixed1);
			// Notebook tab
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("General");
			this.notebook1.SetTabLabel(this.fixed1, this.label1);
			this.label1.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Dual Monitor");
			this.fixed2.Add(this.label10);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label10]));
			w21.X = 65;
			w21.Y = 56;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Audio");
			this.fixed2.Add(this.label11);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label11]));
			w22.X = 65;
			w22.Y = 96;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Protocol");
			this.fixed2.Add(this.label12);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label12]));
			w23.X = 65;
			w23.Y = 136;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Resolution");
			this.fixed2.Add(this.label13);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label13]));
			w24.X = 65;
			w24.Y = 176;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Speed");
			this.fixed2.Add(this.label14);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label14]));
			w25.X = 65;
			w25.Y = 256;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.radioDualOn = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("On"));
			this.radioDualOn.CanFocus = true;
			this.radioDualOn.Name = "radioDualOn";
			this.radioDualOn.DrawIndicator = true;
			this.radioDualOn.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.fixed2.Add(this.radioDualOn);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.radioDualOn]));
			w26.X = 234;
			w26.Y = 56;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.radioDualOff = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Off"));
			this.radioDualOff.CanFocus = true;
			this.radioDualOff.Name = "radioDualOff";
			this.radioDualOff.DrawIndicator = true;
			this.radioDualOff.Group = this.radioDualOn.Group;
			this.fixed2.Add(this.radioDualOff);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.radioDualOff]));
			w27.X = 320;
			w27.Y = 56;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.radioAudioOn = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("On"));
			this.radioAudioOn.CanFocus = true;
			this.radioAudioOn.Name = "radioAudioOn";
			this.radioAudioOn.DrawIndicator = true;
			this.radioAudioOn.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.fixed2.Add(this.radioAudioOn);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.radioAudioOn]));
			w28.X = 234;
			w28.Y = 96;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.radioAudioOff = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Off"));
			this.radioAudioOff.CanFocus = true;
			this.radioAudioOff.Name = "radioAudioOff";
			this.radioAudioOff.DrawIndicator = true;
			this.radioAudioOff.Group = this.radioAudioOn.Group;
			this.fixed2.Add(this.radioAudioOff);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.radioAudioOff]));
			w29.X = 320;
			w29.Y = 96;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.cbxProtocol = global::Gtk.ComboBox.NewText();
			this.cbxProtocol.AppendText(global::Mono.Unix.Catalog.GetString("RDP"));
			this.cbxProtocol.AppendText(global::Mono.Unix.Catalog.GetString("SPICE"));
			this.cbxProtocol.Name = "cbxProtocol";
			this.cbxProtocol.Active = 0;
			this.fixed2.Add(this.cbxProtocol);
			global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.cbxProtocol]));
			w30.X = 234;
			w30.Y = 136;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.cbxResolution = global::Gtk.ComboBox.NewText();
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("600 X 480"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("800 X 600"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("1024 X 768"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("1280 X 768"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("1280 X 1024"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("1440 X 900"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("1600 X 900"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("1600 X 1200"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("1920 X 1080"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("Full Screen"));
			this.cbxResolution.Name = "cbxResolution";
			this.fixed2.Add(this.cbxResolution);
			global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.cbxResolution]));
			w31.X = 234;
			w31.Y = 176;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.cbxSpeed = global::Gtk.ComboBox.NewText();
			this.cbxSpeed.AppendText(global::Mono.Unix.Catalog.GetString("auto"));
			this.cbxSpeed.AppendText(global::Mono.Unix.Catalog.GetString("modem"));
			this.cbxSpeed.AppendText(global::Mono.Unix.Catalog.GetString("broadband"));
			this.cbxSpeed.AppendText(global::Mono.Unix.Catalog.GetString("broadband-low"));
			this.cbxSpeed.AppendText(global::Mono.Unix.Catalog.GetString("broadband-high"));
			this.cbxSpeed.AppendText(global::Mono.Unix.Catalog.GetString("wan"));
			this.cbxSpeed.AppendText(global::Mono.Unix.Catalog.GetString("lan"));
			this.cbxSpeed.Name = "cbxSpeed";
			this.fixed2.Add(this.cbxSpeed);
			global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.cbxSpeed]));
			w32.X = 234;
			w32.Y = 256;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label16 = new global::Gtk.Label();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Color Depth");
			this.fixed2.Add(this.label16);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label16]));
			w33.X = 65;
			w33.Y = 216;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.cbxColorDepth = global::Gtk.ComboBox.NewText();
			this.cbxColorDepth.AppendText(global::Mono.Unix.Catalog.GetString("High Color(15 bpp)"));
			this.cbxColorDepth.AppendText(global::Mono.Unix.Catalog.GetString("High Color(16 bpp)"));
			this.cbxColorDepth.AppendText(global::Mono.Unix.Catalog.GetString("True Color(24 bpp)"));
			this.cbxColorDepth.AppendText(global::Mono.Unix.Catalog.GetString("True Color(32 bpp)"));
			this.cbxColorDepth.Name = "cbxColorDepth";
			this.fixed2.Add(this.cbxColorDepth);
			global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.cbxColorDepth]));
			w34.X = 234;
			w34.Y = 216;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.chkDynamicResolutionUpdate = new global::Gtk.CheckButton();
			this.chkDynamicResolutionUpdate.CanFocus = true;
			this.chkDynamicResolutionUpdate.Name = "chkDynamicResolutionUpdate";
			this.chkDynamicResolutionUpdate.Label = global::Mono.Unix.Catalog.GetString("DynamicResolution");
			this.chkDynamicResolutionUpdate.DrawIndicator = true;
			this.chkDynamicResolutionUpdate.UseUnderline = true;
			this.fixed2.Add(this.chkDynamicResolutionUpdate);
			global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.chkDynamicResolutionUpdate]));
			w35.X = 360;
			w35.Y = 176;
			this.notebook1.Add(this.fixed2);
			global::Gtk.Notebook.NotebookChild w36 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.fixed2]));
			w36.Position = 1;
			// Notebook tab
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Desktop");
			this.notebook1.SetTabLabel(this.fixed2, this.label9);
			this.label9.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Redirect");
			this.fixed3.Add(this.label7);
			global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label7]));
			w37.X = 65;
			w37.Y = 56;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Performance");
			this.fixed3.Add(this.label8);
			global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label8]));
			w38.X = 65;
			w38.Y = 152;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Audio Capture");
			this.fixed3.Add(this.label15);
			global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label15]));
			w39.X = 65;
			w39.Y = 192;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.chkClipboard = new global::Gtk.CheckButton();
			this.chkClipboard.CanFocus = true;
			this.chkClipboard.Name = "chkClipboard";
			this.chkClipboard.Label = global::Mono.Unix.Catalog.GetString("Clipboard");
			this.chkClipboard.DrawIndicator = true;
			this.fixed3.Add(this.chkClipboard);
			global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.chkClipboard]));
			w40.X = 234;
			w40.Y = 56;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.chkLocalPrinter = new global::Gtk.CheckButton();
			this.chkLocalPrinter.CanFocus = true;
			this.chkLocalPrinter.Name = "chkLocalPrinter";
			this.chkLocalPrinter.Label = global::Mono.Unix.Catalog.GetString("Local Printer");
			this.chkLocalPrinter.DrawIndicator = true;
			this.fixed3.Add(this.chkLocalPrinter);
			global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.chkLocalPrinter]));
			w41.X = 350;
			w41.Y = 56;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.chkLocalDriver = new global::Gtk.CheckButton();
			this.chkLocalDriver.CanFocus = true;
			this.chkLocalDriver.Name = "chkLocalDriver";
			this.chkLocalDriver.Label = global::Mono.Unix.Catalog.GetString("Local Driver");
			this.chkLocalDriver.DrawIndicator = true;
			this.fixed3.Add(this.chkLocalDriver);
			global::Gtk.Fixed.FixedChild w42 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.chkLocalDriver]));
			w42.X = 234;
			w42.Y = 78;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.chkLocalDevice = new global::Gtk.CheckButton();
			this.chkLocalDevice.CanFocus = true;
			this.chkLocalDevice.Name = "chkLocalDevice";
			this.chkLocalDevice.Label = global::Mono.Unix.Catalog.GetString("Local Device");
			this.chkLocalDevice.DrawIndicator = true;
			this.fixed3.Add(this.chkLocalDevice);
			global::Gtk.Fixed.FixedChild w43 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.chkLocalDevice]));
			w43.X = 350;
			w43.Y = 100;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.chkLocalPort = new global::Gtk.CheckButton();
			this.chkLocalPort.CanFocus = true;
			this.chkLocalPort.Name = "chkLocalPort";
			this.chkLocalPort.Label = global::Mono.Unix.Catalog.GetString("Local Port");
			this.chkLocalPort.DrawIndicator = true;
			this.fixed3.Add(this.chkLocalPort);
			global::Gtk.Fixed.FixedChild w44 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.chkLocalPort]));
			w44.X = 234;
			w44.Y = 100;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.chkSmartCard = new global::Gtk.CheckButton();
			this.chkSmartCard.CanFocus = true;
			this.chkSmartCard.Name = "chkSmartCard";
			this.chkSmartCard.Label = global::Mono.Unix.Catalog.GetString("Smart Card");
			this.chkSmartCard.DrawIndicator = true;
			this.fixed3.Add(this.chkSmartCard);
			global::Gtk.Fixed.FixedChild w45 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.chkSmartCard]));
			w45.X = 350;
			w45.Y = 78;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.chkBitmapCaching = new global::Gtk.CheckButton();
			this.chkBitmapCaching.CanFocus = true;
			this.chkBitmapCaching.Name = "chkBitmapCaching";
			this.chkBitmapCaching.Label = global::Mono.Unix.Catalog.GetString("Bitmap Caching");
			this.chkBitmapCaching.DrawIndicator = true;
			this.fixed3.Add(this.chkBitmapCaching);
			global::Gtk.Fixed.FixedChild w46 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.chkBitmapCaching]));
			w46.X = 234;
			w46.Y = 152;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.chkMicrophone = new global::Gtk.CheckButton();
			this.chkMicrophone.CanFocus = true;
			this.chkMicrophone.Name = "chkMicrophone";
			this.chkMicrophone.Label = global::Mono.Unix.Catalog.GetString("Local Microphone");
			this.chkMicrophone.DrawIndicator = true;
			this.fixed3.Add(this.chkMicrophone);
			global::Gtk.Fixed.FixedChild w47 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.chkMicrophone]));
			w47.X = 234;
			w47.Y = 192;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.chkVideoCaptureDevice = new global::Gtk.CheckButton();
			this.chkVideoCaptureDevice.CanFocus = true;
			this.chkVideoCaptureDevice.Name = "chkVideoCaptureDevice";
			this.chkVideoCaptureDevice.Label = global::Mono.Unix.Catalog.GetString("Video Capture Device");
			this.chkVideoCaptureDevice.DrawIndicator = true;
			this.chkVideoCaptureDevice.UseUnderline = true;
			this.fixed3.Add(this.chkVideoCaptureDevice);
			global::Gtk.Fixed.FixedChild w48 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.chkVideoCaptureDevice]));
			w48.X = 234;
			w48.Y = 122;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.chkUseRDPEcam = new global::Gtk.CheckButton();
			this.chkUseRDPEcam.CanFocus = true;
			this.chkUseRDPEcam.Name = "chkUseRDPEcam";
			this.chkUseRDPEcam.Label = global::Mono.Unix.Catalog.GetString("Use RDPECAM");
			this.chkUseRDPEcam.DrawIndicator = true;
			this.chkUseRDPEcam.UseUnderline = true;
			this.fixed3.Add(this.chkUseRDPEcam);
			global::Gtk.Fixed.FixedChild w49 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.chkUseRDPEcam]));
			w49.X = 234;
			w49.Y = 232;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Webcam setting");
			this.fixed3.Add(this.label17);
			global::Gtk.Fixed.FixedChild w50 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label17]));
			w50.X = 65;
			w50.Y = 235;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.chkUseH264 = new global::Gtk.CheckButton();
			this.chkUseH264.CanFocus = true;
			this.chkUseH264.Name = "chkUseH264";
			this.chkUseH264.Label = global::Mono.Unix.Catalog.GetString("Use H264");
			this.chkUseH264.DrawIndicator = true;
			this.chkUseH264.UseUnderline = true;
			this.fixed3.Add(this.chkUseH264);
			global::Gtk.Fixed.FixedChild w51 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.chkUseH264]));
			w51.X = 234;
			w51.Y = 254;
			this.notebook1.Add(this.fixed3);
			global::Gtk.Notebook.NotebookChild w52 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.fixed3]));
			w52.Position = 2;
			// Notebook tab
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Resource");
			this.notebook1.SetTabLabel(this.fixed3, this.label2);
			this.label2.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label18 = new global::Gtk.Label();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("General");
			this.fixed4.Add(this.label18);
			global::Gtk.Fixed.FixedChild w53 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.label18]));
			w53.X = 65;
			w53.Y = 56;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.chkExtRDPViewer = new global::Gtk.CheckButton();
			this.chkExtRDPViewer.CanFocus = true;
			this.chkExtRDPViewer.Name = "chkExtRDPViewer";
			this.chkExtRDPViewer.Label = global::Mono.Unix.Catalog.GetString("Use External RDPViewer");
			this.chkExtRDPViewer.DrawIndicator = true;
			this.chkExtRDPViewer.UseUnderline = true;
			this.fixed4.Add(this.chkExtRDPViewer);
			global::Gtk.Fixed.FixedChild w54 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.chkExtRDPViewer]));
			w54.X = 234;
			w54.Y = 56;
			this.notebook1.Add(this.fixed4);
			global::Gtk.Notebook.NotebookChild w55 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.fixed4]));
			w55.Position = 3;
			// Notebook tab
			this.label20 = new global::Gtk.Label();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Others");
			this.notebook1.SetTabLabel(this.fixed4, this.label20);
			this.label20.ShowAll();
			this.Add(this.notebook1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.ButtonNetworkRefresh.Hide();
			this.label15.Hide();
			this.Hide();
			this.cbxLang.Changed += new global::System.EventHandler(this.OnCbxLangChanged);
			this.cbxNetwork.Changed += new global::System.EventHandler(this.OnCbxNetworkChanged);
			this.radioEnableBookmarkOn.Toggled += new global::System.EventHandler(this.OnRadioEnableBookmarkOnGroupChanged);
			this.radioAutoStartOn.Toggled += new global::System.EventHandler(this.OnRadioAutoStartOnGroupChanged);
			this.ButtonNetworkRefresh.Clicked += new global::System.EventHandler(this.ClickNetworkRefresh);
			this.chkAutoClientIP.Toggled += new global::System.EventHandler(this.OnChkAutoClientIPToggled);
			this.radioAutoReconnectOn.Toggled += new global::System.EventHandler(this.OnRadioAutoReconnectOnGroupChanged);
			this.radioDualOn.Toggled += new global::System.EventHandler(this.OnRadioDualOnGroupChanged);
			this.radioAudioOn.Toggled += new global::System.EventHandler(this.OnRadioAudioOnGroupChanged);
			this.cbxProtocol.Changed += new global::System.EventHandler(this.OnCbxProtocolChanged);
			this.cbxResolution.Changed += new global::System.EventHandler(this.OnCbxResolutionChanged);
			this.cbxSpeed.Changed += new global::System.EventHandler(this.OnCbxSpeedChanged);
			this.cbxColorDepth.Changed += new global::System.EventHandler(this.OnCbxColorDepthChanged);
			this.chkDynamicResolutionUpdate.Toggled += new global::System.EventHandler(this.OnChkDynamicResolutionUpdateToggled);
			this.chkClipboard.Toggled += new global::System.EventHandler(this.OnChkClipboardToggled);
			this.chkLocalPrinter.Toggled += new global::System.EventHandler(this.OnChkLocalPrinterToggled);
			this.chkLocalDriver.Toggled += new global::System.EventHandler(this.OnChkLocalDriverToggled);
			this.chkLocalDevice.Toggled += new global::System.EventHandler(this.OnChkLocalDeviceToggled);
			this.chkLocalPort.Toggled += new global::System.EventHandler(this.OnChkLocalPortToggled);
			this.chkSmartCard.Toggled += new global::System.EventHandler(this.OnChkSmartCardToggled);
			this.chkBitmapCaching.Toggled += new global::System.EventHandler(this.OnChkBitmapCachingToggled);
			this.chkMicrophone.Toggled += new global::System.EventHandler(this.OnChkMicrophoneToggled);
			this.chkVideoCaptureDevice.Toggled += new global::System.EventHandler(this.OnChkVideoCaptureDeviceToggled);
			this.chkUseRDPEcam.Toggled += new global::System.EventHandler(this.OnChkUseRDPEcamToggled);
			this.chkUseH264.Toggled += new global::System.EventHandler(this.OnChkUseH264Toggled);
			this.chkExtRDPViewer.Toggled += new global::System.EventHandler(this.OnChkExtRDPViewerToggled);
		}
	}
}
