
// This file has been generated by the GUI designer. Do not modify.
namespace client
{
	public partial class serverlistWidget
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.EventBox eventboxServerlist;

		private global::Gtk.VBox vbox5;

		private global::Gtk.ScrolledWindow scrollServerlist;

		private global::Gtk.VBox vboxServerlist;

		private global::Gtk.Button btnAddServer;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget client.serverlistWidget
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 256;
			this.HeightRequest = 377;
			this.Name = "client.serverlistWidget";
			// Container child client.serverlistWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.eventboxServerlist = new global::Gtk.EventBox();
			this.eventboxServerlist.Name = "eventboxServerlist";
			// Container child eventboxServerlist.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.scrollServerlist = new global::Gtk.ScrolledWindow();
			this.scrollServerlist.CanFocus = true;
			this.scrollServerlist.Name = "scrollServerlist";
			this.scrollServerlist.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			// Container child scrollServerlist.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vboxServerlist = new global::Gtk.VBox();
			this.vboxServerlist.Name = "vboxServerlist";
			this.vboxServerlist.Spacing = 6;
			w1.Add(this.vboxServerlist);
			this.scrollServerlist.Add(w1);
			this.vbox5.Add(this.scrollServerlist);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.scrollServerlist]));
			w4.Position = 0;
			// Container child vbox5.Gtk.Box+BoxChild
			this.btnAddServer = new global::Gtk.Button();
			this.btnAddServer.HeightRequest = 50;
			this.btnAddServer.CanFocus = true;
			this.btnAddServer.Name = "btnAddServer";
			this.btnAddServer.Label = global::Mono.Unix.Catalog.GetString("ADD SERVER");
			global::Gtk.Image w5 = new global::Gtk.Image();
			w5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("client.Resources.icon_add_enable.png");
			this.btnAddServer.Image = w5;
			this.vbox5.Add(this.btnAddServer);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.btnAddServer]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.eventboxServerlist.Add(this.vbox5);
			this.vbox2.Add(this.eventboxServerlist);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.eventboxServerlist]));
			w8.Position = 0;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.scrollServerlist.Hide();
			this.Hide();
			this.scrollServerlist.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.OnScrollServerlistButtonPressEvent);
			this.btnAddServer.Clicked += new global::System.EventHandler(this.OnbtnAddServerClicked);
		}
	}
}
