
// This file has been generated by the GUI designer. Do not modify.
namespace client
{
	public partial class logInWidget
	{
		private global::Gtk.EventBox eventbox3;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label10;

		private global::Gtk.Label label11;

		private global::Gtk.Label label12;

		private global::Gtk.Label label13;

		private global::Gtk.Label label14;

		private global::Gtk.Label label15;

		private global::Gtk.Entry tbxServerName;

		private global::Gtk.Entry tbxServerIP;

		private global::Gtk.Entry tbxServerPort;

		private global::Gtk.Entry tbxUserID;

		private global::Gtk.Entry tbxPassword;

		private global::Gtk.Button btnCancel;

		private global::Gtk.Button btnLogin;

		private global::Gtk.CheckButton chkIDSave;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget client.logInWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "client.logInWidget";
			// Container child client.logInWidget.Gtk.Container+ContainerChild
			this.eventbox3 = new global::Gtk.EventBox();
			this.eventbox3.Name = "eventbox3";
			// Container child eventbox3.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.WidthRequest = 256;
			this.fixed1.HeightRequest = 377;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\'14000\'>Login</span>");
			this.label10.UseMarkup = true;
			this.fixed1.Add(this.label10);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label10]));
			w1.X = 107;
			w1.Y = 24;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Server Name");
			this.fixed1.Add(this.label11);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label11]));
			w2.X = 10;
			w2.Y = 69;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Server IP");
			this.fixed1.Add(this.label12);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label12]));
			w3.X = 10;
			w3.Y = 109;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Server Port");
			this.fixed1.Add(this.label13);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label13]));
			w4.X = 10;
			w4.Y = 149;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("User ID");
			this.fixed1.Add(this.label14);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label14]));
			w5.X = 10;
			w5.Y = 189;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Password");
			this.fixed1.Add(this.label15);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label15]));
			w6.X = 10;
			w6.Y = 229;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbxServerName = new global::Gtk.Entry();
			this.tbxServerName.WidthRequest = 136;
			this.tbxServerName.Sensitive = false;
			this.tbxServerName.CanFocus = true;
			this.tbxServerName.Name = "tbxServerName";
			this.tbxServerName.IsEditable = true;
			this.tbxServerName.InvisibleChar = '•';
			this.fixed1.Add(this.tbxServerName);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tbxServerName]));
			w7.X = 113;
			w7.Y = 69;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbxServerIP = new global::Gtk.Entry();
			this.tbxServerIP.WidthRequest = 136;
			this.tbxServerIP.Sensitive = false;
			this.tbxServerIP.CanFocus = true;
			this.tbxServerIP.Name = "tbxServerIP";
			this.tbxServerIP.IsEditable = true;
			this.tbxServerIP.InvisibleChar = '•';
			this.fixed1.Add(this.tbxServerIP);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tbxServerIP]));
			w8.X = 113;
			w8.Y = 109;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbxServerPort = new global::Gtk.Entry();
			this.tbxServerPort.WidthRequest = 136;
			this.tbxServerPort.Sensitive = false;
			this.tbxServerPort.CanFocus = true;
			this.tbxServerPort.Name = "tbxServerPort";
			this.tbxServerPort.IsEditable = true;
			this.tbxServerPort.InvisibleChar = '•';
			this.fixed1.Add(this.tbxServerPort);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tbxServerPort]));
			w9.X = 113;
			w9.Y = 149;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbxUserID = new global::Gtk.Entry();
			this.tbxUserID.WidthRequest = 136;
			this.tbxUserID.CanFocus = true;
			this.tbxUserID.Name = "tbxUserID";
			this.tbxUserID.IsEditable = true;
			this.tbxUserID.InvisibleChar = '•';
			this.fixed1.Add(this.tbxUserID);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tbxUserID]));
			w10.X = 113;
			w10.Y = 189;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbxPassword = new global::Gtk.Entry();
			this.tbxPassword.WidthRequest = 136;
			this.tbxPassword.CanFocus = true;
			this.tbxPassword.Name = "tbxPassword";
			this.tbxPassword.IsEditable = true;
			this.tbxPassword.Visibility = false;
			this.tbxPassword.InvisibleChar = '•';
			this.fixed1.Add(this.tbxPassword);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tbxPassword]));
			w11.X = 113;
			w11.Y = 229;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnCancel = new global::Gtk.Button();
			this.btnCancel.WidthRequest = 100;
			this.btnCancel.HeightRequest = 34;
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.Label = global::Mono.Unix.Catalog.GetString("CANCEL");
			this.fixed1.Add(this.btnCancel);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnCancel]));
			w12.X = 25;
			w12.Y = 300;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnLogin = new global::Gtk.Button();
			this.btnLogin.WidthRequest = 100;
			this.btnLogin.HeightRequest = 34;
			this.btnLogin.CanFocus = true;
			this.btnLogin.Name = "btnLogin";
			this.btnLogin.Label = global::Mono.Unix.Catalog.GetString("LOGIN");
			this.fixed1.Add(this.btnLogin);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnLogin]));
			w13.X = 131;
			w13.Y = 300;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.chkIDSave = new global::Gtk.CheckButton();
			this.chkIDSave.CanFocus = true;
			this.chkIDSave.Name = "chkIDSave";
			this.chkIDSave.Label = global::Mono.Unix.Catalog.GetString("Remember ID");
			this.chkIDSave.DrawIndicator = true;
			this.chkIDSave.UseUnderline = true;
			this.fixed1.Add(this.chkIDSave);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkIDSave]));
			w14.X = 10;
			w14.Y = 269;
			this.eventbox3.Add(this.fixed1);
			this.Add(this.eventbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.tbxUserID.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnTbxUserIDKeyPressEvent);
			this.tbxPassword.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnTbxPasswordKeyPressEvent);
			this.btnCancel.Clicked += new global::System.EventHandler(this.OnBtnCancelClicked);
			this.btnLogin.Clicked += new global::System.EventHandler(this.OnBtnLoginClicked);
		}
	}
}
