
// This file has been generated by the GUI designer. Do not modify.
namespace client
{
	public partial class editDesktopPageWidget
	{
		private global::Gtk.EventBox eventbox4;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Label label19;

		private global::Gtk.Label label20;

		private global::Gtk.Label label21;

		private global::Gtk.Label label22;

		private global::Gtk.Label label23;

		private global::Gtk.Label label24;

		private global::Gtk.Label label25;

		private global::Gtk.Entry tbxIP;

		private global::Gtk.Entry tbxType;

		private global::Gtk.ComboBox cbxProtocol;

		private global::Gtk.ComboBox cbxResolution;

		private global::Gtk.RadioButton radioAudioOn;

		private global::Gtk.RadioButton radioAudioOff;

		private global::Gtk.ComboBox cbxSpeed;

		private global::Gtk.Button btnCancel;

		private global::Gtk.Button btnOK;

		private global::Gtk.Entry tbxName;

		private global::Gtk.Label label18;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget client.editDesktopPageWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "client.editDesktopPageWidget";
			// Container child client.editDesktopPageWidget.Gtk.Container+ContainerChild
			this.eventbox4 = new global::Gtk.EventBox();
			this.eventbox4.Name = "eventbox4";
			// Container child eventbox4.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.WidthRequest = 256;
			this.fixed2.HeightRequest = 377;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Name");
			this.fixed2.Add(this.label19);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label19]));
			w1.X = 12;
			w1.Y = 50;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label20 = new global::Gtk.Label();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("IP");
			this.fixed2.Add(this.label20);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label20]));
			w2.X = 12;
			w2.Y = 82;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Type");
			this.fixed2.Add(this.label21);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label21]));
			w3.X = 12;
			w3.Y = 114;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label22 = new global::Gtk.Label();
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("Protocol");
			this.fixed2.Add(this.label22);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label22]));
			w4.X = 12;
			w4.Y = 144;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label23 = new global::Gtk.Label();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("Resolution");
			this.fixed2.Add(this.label23);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label23]));
			w5.X = 12;
			w5.Y = 174;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label24 = new global::Gtk.Label();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("Audio");
			this.fixed2.Add(this.label24);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label24]));
			w6.X = 12;
			w6.Y = 204;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label25 = new global::Gtk.Label();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("Speed");
			this.fixed2.Add(this.label25);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label25]));
			w7.X = 12;
			w7.Y = 234;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.tbxIP = new global::Gtk.Entry();
			this.tbxIP.CanFocus = true;
			this.tbxIP.Name = "tbxIP";
			this.tbxIP.IsEditable = false;
			this.tbxIP.InvisibleChar = '•';
			this.fixed2.Add(this.tbxIP);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.tbxIP]));
			w8.X = 93;
			w8.Y = 80;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.tbxType = new global::Gtk.Entry();
			this.tbxType.CanFocus = true;
			this.tbxType.Name = "tbxType";
			this.tbxType.IsEditable = false;
			this.tbxType.InvisibleChar = '•';
			this.fixed2.Add(this.tbxType);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.tbxType]));
			w9.X = 93;
			w9.Y = 110;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.cbxProtocol = global::Gtk.ComboBox.NewText();
			this.cbxProtocol.AppendText(global::Mono.Unix.Catalog.GetString("RDP"));
			this.cbxProtocol.AppendText(global::Mono.Unix.Catalog.GetString("SPICE"));
			this.cbxProtocol.Name = "cbxProtocol";
			this.cbxProtocol.Active = 0;
			this.fixed2.Add(this.cbxProtocol);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.cbxProtocol]));
			w10.X = 93;
			w10.Y = 140;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.cbxResolution = global::Gtk.ComboBox.NewText();
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("600 X 480"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("800 X 600"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("1024 X 768"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("1280 X 768"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("1280 X 1024"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("1440 X 900"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("1600 X 900"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("1600 X 1200"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("1920 X 1080"));
			this.cbxResolution.AppendText(global::Mono.Unix.Catalog.GetString("Full Screen"));
			this.cbxResolution.Name = "cbxResolution";
			this.cbxResolution.Active = 0;
			this.fixed2.Add(this.cbxResolution);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.cbxResolution]));
			w11.X = 93;
			w11.Y = 170;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.radioAudioOn = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("on"));
			this.radioAudioOn.CanFocus = true;
			this.radioAudioOn.Name = "radioAudioOn";
			this.radioAudioOn.DrawIndicator = true;
			this.radioAudioOn.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.fixed2.Add(this.radioAudioOn);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.radioAudioOn]));
			w12.X = 93;
			w12.Y = 200;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.radioAudioOff = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("off"));
			this.radioAudioOff.CanFocus = true;
			this.radioAudioOff.Name = "radioAudioOff";
			this.radioAudioOff.DrawIndicator = true;
			this.radioAudioOff.Group = this.radioAudioOn.Group;
			this.fixed2.Add(this.radioAudioOff);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.radioAudioOff]));
			w13.X = 143;
			w13.Y = 200;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.cbxSpeed = global::Gtk.ComboBox.NewText();
			this.cbxSpeed.AppendText(global::Mono.Unix.Catalog.GetString("auto"));
			this.cbxSpeed.AppendText(global::Mono.Unix.Catalog.GetString("modem"));
			this.cbxSpeed.AppendText(global::Mono.Unix.Catalog.GetString("broadband"));
			this.cbxSpeed.AppendText(global::Mono.Unix.Catalog.GetString("broadband-low"));
			this.cbxSpeed.AppendText(global::Mono.Unix.Catalog.GetString("broadband-high"));
			this.cbxSpeed.AppendText(global::Mono.Unix.Catalog.GetString("wan"));
			this.cbxSpeed.AppendText(global::Mono.Unix.Catalog.GetString("lan"));
			this.cbxSpeed.Name = "cbxSpeed";
			this.fixed2.Add(this.cbxSpeed);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.cbxSpeed]));
			w14.X = 93;
			w14.Y = 230;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnCancel = new global::Gtk.Button();
			this.btnCancel.WidthRequest = 100;
			this.btnCancel.HeightRequest = 34;
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.Label = global::Mono.Unix.Catalog.GetString("CANCEL");
			this.fixed2.Add(this.btnCancel);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnCancel]));
			w15.X = 25;
			w15.Y = 285;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnOK = new global::Gtk.Button();
			this.btnOK.WidthRequest = 100;
			this.btnOK.HeightRequest = 34;
			this.btnOK.CanFocus = true;
			this.btnOK.Name = "btnOK";
			this.btnOK.Label = global::Mono.Unix.Catalog.GetString("OK");
			this.fixed2.Add(this.btnOK);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnOK]));
			w16.X = 130;
			w16.Y = 285;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.tbxName = new global::Gtk.Entry();
			this.tbxName.CanFocus = true;
			this.tbxName.Name = "tbxName";
			this.tbxName.IsEditable = true;
			this.tbxName.InvisibleChar = '•';
			this.fixed2.Add(this.tbxName);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.tbxName]));
			w17.X = 93;
			w17.Y = 50;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label18 = new global::Gtk.Label();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\'14000\'>Edit Desktop Attributes</span>");
			this.label18.UseMarkup = true;
			this.fixed2.Add(this.label18);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label18]));
			w18.X = 44;
			w18.Y = 14;
			this.eventbox4.Add(this.fixed2);
			this.Add(this.eventbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.btnCancel.Clicked += new global::System.EventHandler(this.OnBtnCancelClicked);
			this.btnOK.Clicked += new global::System.EventHandler(this.OnBtnOKClicked);
		}
	}
}
