
// This file has been generated by the GUI designer. Do not modify.
namespace client
{
	public partial class InfoWindow
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label labelDxClientVesion;

		private global::Gtk.Label labelDaaSXpertVersion;

		private global::Gtk.Label labelFileVersion;

		private global::Gtk.Label labelBuildDate;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget client.InfoWindow
			this.Name = "client.InfoWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Version Information");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(2));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Container child client.InfoWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelDxClientVesion = new global::Gtk.Label();
			this.labelDxClientVesion.WidthRequest = 200;
			this.labelDxClientVesion.Name = "labelDxClientVesion";
			this.labelDxClientVesion.LabelProp = global::Mono.Unix.Catalog.GetString("dxClient Version");
			this.labelDxClientVesion.Justify = ((global::Gtk.Justification)(2));
			this.fixed1.Add(this.labelDxClientVesion);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.labelDxClientVesion]));
			w1.X = 5;
			w1.Y = 60;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelDaaSXpertVersion = new global::Gtk.Label();
			this.labelDaaSXpertVersion.WidthRequest = 200;
			this.labelDaaSXpertVersion.Name = "labelDaaSXpertVersion";
			this.labelDaaSXpertVersion.LabelProp = global::Mono.Unix.Catalog.GetString("DaaSXpert Ver. 3.0");
			this.labelDaaSXpertVersion.Justify = ((global::Gtk.Justification)(2));
			this.fixed1.Add(this.labelDaaSXpertVersion);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.labelDaaSXpertVersion]));
			w2.X = 5;
			w2.Y = 20;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelFileVersion = new global::Gtk.Label();
			this.labelFileVersion.WidthRequest = 200;
			this.labelFileVersion.Name = "labelFileVersion";
			this.labelFileVersion.LabelProp = global::Mono.Unix.Catalog.GetString("File Version : 3.0.0.000");
			this.fixed1.Add(this.labelFileVersion);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.labelFileVersion]));
			w3.X = 5;
			w3.Y = 100;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelBuildDate = new global::Gtk.Label();
			this.labelBuildDate.WidthRequest = 200;
			this.labelBuildDate.Name = "labelBuildDate";
			this.labelBuildDate.LabelProp = global::Mono.Unix.Catalog.GetString("Build Date 0000-00-00");
			this.fixed1.Add(this.labelBuildDate);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.labelBuildDate]));
			w4.X = 5;
			w4.Y = 140;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 220;
			this.DefaultHeight = 179;
			this.Show();
		}
	}
}
