
// This file has been generated by the GUI designer. Do not modify.
namespace client
{
	public partial class addServerPageWidget
	{
		private global::Gtk.EventBox eventbox2;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label labelTitle;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Entry tbxServerName;

		private global::Gtk.Entry tbxServerIP;

		private global::Gtk.Entry tbxServerPort;

		private global::Gtk.Button btnCancel;

		private global::Gtk.Button btnAdd;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget client.addServerPageWidget
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 256;
			this.HeightRequest = 377;
			this.Name = "client.addServerPageWidget";
			// Container child client.addServerPageWidget.Gtk.Container+ContainerChild
			this.eventbox2 = new global::Gtk.EventBox();
			this.eventbox2.Name = "eventbox2";
			// Container child eventbox2.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelTitle = new global::Gtk.Label();
			this.labelTitle.WidthRequest = 150;
			this.labelTitle.HeightRequest = 24;
			this.labelTitle.Name = "labelTitle";
			this.labelTitle.Xalign = 0F;
			this.labelTitle.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\'14000\'>Add Server</span>");
			this.labelTitle.UseMarkup = true;
			this.fixed1.Add(this.labelTitle);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.labelTitle]));
			w1.X = 80;
			w1.Y = 28;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.WidthRequest = 98;
			this.label2.HeightRequest = 32;
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Server Name");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w2.X = 10;
			w2.Y = 69;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.WidthRequest = 98;
			this.label3.HeightRequest = 24;
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Server IP");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w3.X = 10;
			w3.Y = 109;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.WidthRequest = 98;
			this.label4.HeightRequest = 24;
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Server Port");
			this.fixed1.Add(this.label4);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
			w4.X = 10;
			w4.Y = 149;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbxServerName = new global::Gtk.Entry();
			this.tbxServerName.WidthRequest = 136;
			this.tbxServerName.HeightRequest = 32;
			this.tbxServerName.CanFocus = true;
			this.tbxServerName.Name = "tbxServerName";
			this.tbxServerName.IsEditable = true;
			this.tbxServerName.InvisibleChar = '•';
			this.fixed1.Add(this.tbxServerName);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tbxServerName]));
			w5.X = 110;
			w5.Y = 69;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbxServerIP = new global::Gtk.Entry();
			this.tbxServerIP.WidthRequest = 136;
			this.tbxServerIP.HeightRequest = 32;
			this.tbxServerIP.CanFocus = true;
			this.tbxServerIP.Name = "tbxServerIP";
			this.tbxServerIP.IsEditable = true;
			this.tbxServerIP.InvisibleChar = '•';
			this.fixed1.Add(this.tbxServerIP);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tbxServerIP]));
			w6.X = 110;
			w6.Y = 109;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbxServerPort = new global::Gtk.Entry();
			this.tbxServerPort.WidthRequest = 136;
			this.tbxServerPort.HeightRequest = 32;
			this.tbxServerPort.CanFocus = true;
			this.tbxServerPort.Name = "tbxServerPort";
			this.tbxServerPort.IsEditable = true;
			this.tbxServerPort.InvisibleChar = '•';
			this.fixed1.Add(this.tbxServerPort);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tbxServerPort]));
			w7.X = 110;
			w7.Y = 149;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnCancel = new global::Gtk.Button();
			this.btnCancel.WidthRequest = 100;
			this.btnCancel.HeightRequest = 34;
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.Label = global::Mono.Unix.Catalog.GetString("CANCEL");
			this.fixed1.Add(this.btnCancel);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnCancel]));
			w8.X = 25;
			w8.Y = 293;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnAdd = new global::Gtk.Button();
			this.btnAdd.WidthRequest = 100;
			this.btnAdd.HeightRequest = 34;
			this.btnAdd.CanFocus = true;
			this.btnAdd.Name = "btnAdd";
			this.btnAdd.Label = global::Mono.Unix.Catalog.GetString("ADD");
			this.fixed1.Add(this.btnAdd);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnAdd]));
			w9.X = 131;
			w9.Y = 293;
			this.eventbox2.Add(this.fixed1);
			this.Add(this.eventbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.btnCancel.Clicked += new global::System.EventHandler(this.OnBtnCancelAddServerClicked);
			this.btnAdd.Clicked += new global::System.EventHandler(this.OnBtnOKAddServerClicked);
		}
	}
}
