
// This file has been generated by the GUI designer. Do not modify.
namespace client
{
	public partial class desktopPolicyWidget
	{
		private global::Gtk.EventBox eventbox;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label labelTitle;

		private global::Gtk.Button btnOK;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.VBox vboxlist;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label;

		private global::Gtk.Image image;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget client.desktopPolicyWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "client.desktopPolicyWidget";
			// Container child client.desktopPolicyWidget.Gtk.Container+ContainerChild
			this.eventbox = new global::Gtk.EventBox();
			this.eventbox.Name = "eventbox";
			// Container child eventbox.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelTitle = new global::Gtk.Label();
			this.labelTitle.Name = "labelTitle";
			this.labelTitle.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\'14000\'>Desktop Policies</span>");
			this.labelTitle.UseMarkup = true;
			this.fixed1.Add(this.labelTitle);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.labelTitle]));
			w1.X = 45;
			w1.Y = 21;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnOK = new global::Gtk.Button();
			this.btnOK.WidthRequest = 206;
			this.btnOK.HeightRequest = 34;
			this.btnOK.CanFocus = true;
			this.btnOK.Name = "btnOK";
			this.btnOK.Label = global::Mono.Unix.Catalog.GetString("OK");
			this.fixed1.Add(this.btnOK);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnOK]));
			w2.X = 25;
			w2.Y = 323;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.WidthRequest = 247;
			this.scrolledwindow1.HeightRequest = 260;
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.scrolledwindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w3 = new global::Gtk.Viewport();
			w3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vboxlist = new global::Gtk.VBox();
			this.vboxlist.Name = "vboxlist";
			this.vboxlist.Spacing = 6;
			// Container child vboxlist.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label = new global::Gtk.Label();
			this.label.WidthRequest = 180;
			this.label.HeightRequest = 25;
			this.label.Name = "label";
			this.label.Xalign = 0F;
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this.hbox1.Add(this.label);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image = new global::Gtk.Image();
			this.image.Name = "image";
			this.image.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("client.Resources.switch_2_on.png");
			this.hbox1.Add(this.image);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.image]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vboxlist.Add(this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxlist[this.hbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			w3.Add(this.vboxlist);
			this.scrolledwindow1.Add(w3);
			this.fixed1.Add(this.scrolledwindow1);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.scrolledwindow1]));
			w9.X = 5;
			w9.Y = 55;
			this.eventbox.Add(this.fixed1);
			this.Add(this.eventbox);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.btnOK.Clicked += new global::System.EventHandler(this.OnBtnOKClicked);
		}
	}
}
