
// This file has been generated by the GUI designer. Do not modify.
namespace client
{
	public partial class leftMenuItemWidget
	{
		private global::Gtk.EventBox eventbox;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Image imageIcon;

		private global::Gtk.Label labelTitle;

		private global::Gtk.Image imageArrow;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget client.leftMenuItemWidget
			global::Stetic.BinContainer.Attach(this);
			this.HeightRequest = 40;
			this.Name = "client.leftMenuItemWidget";
			// Container child client.leftMenuItemWidget.Gtk.Container+ContainerChild
			this.eventbox = new global::Gtk.EventBox();
			this.eventbox.Name = "eventbox";
			// Container child eventbox.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.imageIcon = new global::Gtk.Image();
			this.imageIcon.Name = "imageIcon";
			this.fixed1.Add(this.imageIcon);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.imageIcon]));
			w1.X = 16;
			w1.Y = 10;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelTitle = new global::Gtk.Label();
			this.labelTitle.WidthRequest = 130;
			this.labelTitle.Name = "labelTitle";
			this.labelTitle.Xalign = 0F;
			this.labelTitle.Yalign = 0F;
			this.labelTitle.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\'15500\'>HOME</span>");
			this.labelTitle.UseMarkup = true;
			this.fixed1.Add(this.labelTitle);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.labelTitle]));
			w2.X = 50;
			w2.Y = 8;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.imageArrow = new global::Gtk.Image();
			this.imageArrow.Name = "imageArrow";
			this.fixed1.Add(this.imageArrow);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.imageArrow]));
			w3.X = 237;
			w3.Y = 14;
			this.eventbox.Add(this.fixed1);
			this.Add(this.eventbox);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.eventbox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.OnEventboxButtonPressEvent);
			this.eventbox.EnterNotifyEvent += new global::Gtk.EnterNotifyEventHandler(this.OnEventboxEnterNotifyEvent);
			this.eventbox.LeaveNotifyEvent += new global::Gtk.LeaveNotifyEventHandler(this.OnEventboxLeaveNotifyEvent);
		}
	}
}
