
// This file has been generated by the GUI designer. Do not modify.
namespace client
{
	public partial class ChangePasswordWidget
	{
		private global::Gtk.EventBox eventbox_changepassword;

		private global::Gtk.Fixed fixed_changepassword;

		private global::Gtk.Label lb_ChangePasswordTitle;

		private global::Gtk.Entry entry_CurPassword;

		private global::Gtk.Label lb_CurPassword;

		private global::Gtk.Label lb_ConfirmNewPassword;

		private global::Gtk.Entry entry_ConfirmNewPassword;

		private global::Gtk.Label lb_NewPassword;

		private global::Gtk.Entry entry_NewPassword;

		private global::Gtk.Label lb_ErrorMessage;

		private global::Gtk.Label lb_ReasonMessage;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget client.ChangePasswordWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "client.ChangePasswordWidget";
			// Container child client.ChangePasswordWidget.Gtk.Container+ContainerChild
			this.eventbox_changepassword = new global::Gtk.EventBox();
			this.eventbox_changepassword.Name = "eventbox_changepassword";
			// Container child eventbox_changepassword.Gtk.Container+ContainerChild
			this.fixed_changepassword = new global::Gtk.Fixed();
			this.fixed_changepassword.Name = "fixed_changepassword";
			this.fixed_changepassword.HasWindow = false;
			// Container child fixed_changepassword.Gtk.Fixed+FixedChild
			this.lb_ChangePasswordTitle = new global::Gtk.Label();
			this.lb_ChangePasswordTitle.Name = "lb_ChangePasswordTitle";
			this.lb_ChangePasswordTitle.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\'14000\'>Change Password</span>");
			this.lb_ChangePasswordTitle.UseMarkup = true;
			this.fixed_changepassword.Add(this.lb_ChangePasswordTitle);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed_changepassword[this.lb_ChangePasswordTitle]));
			w1.X = 60;
			// Container child fixed_changepassword.Gtk.Fixed+FixedChild
			this.entry_CurPassword = new global::Gtk.Entry();
			this.entry_CurPassword.CanFocus = true;
			this.entry_CurPassword.Name = "entry_CurPassword";
			this.entry_CurPassword.IsEditable = true;
			this.entry_CurPassword.MaxLength = 30;
			this.entry_CurPassword.InvisibleChar = '●';
			this.fixed_changepassword.Add(this.entry_CurPassword);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed_changepassword[this.entry_CurPassword]));
			w2.X = 60;
			w2.Y = 75;
			// Container child fixed_changepassword.Gtk.Fixed+FixedChild
			this.lb_CurPassword = new global::Gtk.Label();
			this.lb_CurPassword.Name = "lb_CurPassword";
			this.lb_CurPassword.LabelProp = global::Mono.Unix.Catalog.GetString("Current Password");
			this.fixed_changepassword.Add(this.lb_CurPassword);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed_changepassword[this.lb_CurPassword]));
			w3.X = 60;
			w3.Y = 50;
			// Container child fixed_changepassword.Gtk.Fixed+FixedChild
			this.lb_ConfirmNewPassword = new global::Gtk.Label();
			this.lb_ConfirmNewPassword.Name = "lb_ConfirmNewPassword";
			this.lb_ConfirmNewPassword.LabelProp = global::Mono.Unix.Catalog.GetString("Confirm New Password");
			this.fixed_changepassword.Add(this.lb_ConfirmNewPassword);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed_changepassword[this.lb_ConfirmNewPassword]));
			w4.X = 60;
			w4.Y = 171;
			// Container child fixed_changepassword.Gtk.Fixed+FixedChild
			this.entry_ConfirmNewPassword = new global::Gtk.Entry();
			this.entry_ConfirmNewPassword.CanFocus = true;
			this.entry_ConfirmNewPassword.Name = "entry_ConfirmNewPassword";
			this.entry_ConfirmNewPassword.IsEditable = true;
			this.entry_ConfirmNewPassword.MaxLength = 30;
			this.entry_ConfirmNewPassword.InvisibleChar = '●';
			this.fixed_changepassword.Add(this.entry_ConfirmNewPassword);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed_changepassword[this.entry_ConfirmNewPassword]));
			w5.X = 60;
			w5.Y = 195;
			// Container child fixed_changepassword.Gtk.Fixed+FixedChild
			this.lb_NewPassword = new global::Gtk.Label();
			this.lb_NewPassword.Name = "lb_NewPassword";
			this.lb_NewPassword.LabelProp = global::Mono.Unix.Catalog.GetString("New Password");
			this.fixed_changepassword.Add(this.lb_NewPassword);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed_changepassword[this.lb_NewPassword]));
			w6.X = 60;
			w6.Y = 110;
			// Container child fixed_changepassword.Gtk.Fixed+FixedChild
			this.entry_NewPassword = new global::Gtk.Entry();
			this.entry_NewPassword.CanFocus = true;
			this.entry_NewPassword.Name = "entry_NewPassword";
			this.entry_NewPassword.IsEditable = true;
			this.entry_NewPassword.MaxLength = 30;
			this.entry_NewPassword.InvisibleChar = '●';
			this.fixed_changepassword.Add(this.entry_NewPassword);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed_changepassword[this.entry_NewPassword]));
			w7.X = 60;
			w7.Y = 135;
			// Container child fixed_changepassword.Gtk.Fixed+FixedChild
			this.lb_ErrorMessage = new global::Gtk.Label();
			this.lb_ErrorMessage.WidthRequest = 250;
			this.lb_ErrorMessage.HeightRequest = 60;
			this.lb_ErrorMessage.Name = "lb_ErrorMessage";
			this.lb_ErrorMessage.LabelProp = global::Mono.Unix.Catalog.GetString("Error");
			this.lb_ErrorMessage.UseMarkup = true;
			this.lb_ErrorMessage.Wrap = true;
			this.fixed_changepassword.Add(this.lb_ErrorMessage);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed_changepassword[this.lb_ErrorMessage]));
			w8.X = 10;
			w8.Y = 234;
			// Container child fixed_changepassword.Gtk.Fixed+FixedChild
			this.lb_ReasonMessage = new global::Gtk.Label();
			this.lb_ReasonMessage.Name = "lb_ReasonMessage";
			this.lb_ReasonMessage.LabelProp = global::Mono.Unix.Catalog.GetString("Reason");
			this.lb_ReasonMessage.UseMarkup = true;
			this.fixed_changepassword.Add(this.lb_ReasonMessage);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed_changepassword[this.lb_ReasonMessage]));
			w9.X = 10;
			w9.Y = 27;
			this.eventbox_changepassword.Add(this.fixed_changepassword);
			this.Add(this.eventbox_changepassword);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.entry_CurPassword.Hide();
			this.entry_ConfirmNewPassword.Hide();
			this.entry_NewPassword.Hide();
			this.Hide();
			this.entry_ConfirmNewPassword.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnEntryConfirmNewPasswordKeyPressEvent);
		}
	}
}
