
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox3;

	private global::Gtk.EventBox eventboxTitlebar;

	private global::Gtk.Fixed fixed7;

	private global::Gtk.Image imageTitle;

	private global::Gtk.Label labelTitlebar;

	private global::Gtk.EventBox eventboxClose;

	private global::Gtk.Image imageClose;

	private global::Gtk.HBox hbox2;

	private global::client.leftMenuWidget leftmenuwidget1;

	private global::Gtk.VBox vboxPage;

	private global::Gtk.EventBox eventboxState;

	private global::Gtk.Label labelState;

	private global::Gtk.Image image28;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("DaaSXpert Client");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource("client.Resources.daasxpert.icon-48.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 788;
		this.DefaultHeight = 589;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.eventboxTitlebar = new global::Gtk.EventBox();
		this.eventboxTitlebar.HeightRequest = 29;
		this.eventboxTitlebar.Name = "eventboxTitlebar";
		// Container child eventboxTitlebar.Gtk.Container+ContainerChild
		this.fixed7 = new global::Gtk.Fixed();
		this.fixed7.Name = "fixed7";
		this.fixed7.HasWindow = false;
		// Container child fixed7.Gtk.Fixed+FixedChild
		this.imageTitle = new global::Gtk.Image();
		this.imageTitle.Name = "imageTitle";
		this.imageTitle.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("client.Resources.dassxpert_icon.png");
		this.fixed7.Add(this.imageTitle);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.imageTitle]));
		w1.X = 14;
		w1.Y = 10;
		// Container child fixed7.Gtk.Fixed+FixedChild
		this.labelTitlebar = new global::Gtk.Label();
		this.labelTitlebar.Name = "labelTitlebar";
		this.labelTitlebar.LabelProp = global::Mono.Unix.Catalog.GetString("DaaSXpert Client");
		this.fixed7.Add(this.labelTitlebar);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.labelTitlebar]));
		w2.X = 34;
		w2.Y = 7;
		// Container child fixed7.Gtk.Fixed+FixedChild
		this.eventboxClose = new global::Gtk.EventBox();
		this.eventboxClose.WidthRequest = 10;
		this.eventboxClose.HeightRequest = 10;
		this.eventboxClose.Name = "eventboxClose";
		// Container child eventboxClose.Gtk.Container+ContainerChild
		this.imageClose = new global::Gtk.Image();
		this.imageClose.Name = "imageClose";
		this.imageClose.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("client.Resources.window_close.png");
		this.eventboxClose.Add(this.imageClose);
		this.fixed7.Add(this.eventboxClose);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.eventboxClose]));
		w4.X = 745;
		w4.Y = 10;
		this.eventboxTitlebar.Add(this.fixed7);
		this.vbox3.Add(this.eventboxTitlebar);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.eventboxTitlebar]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.leftmenuwidget1 = new global::client.leftMenuWidget();
		this.leftmenuwidget1.WidthRequest = 256;
		this.leftmenuwidget1.HeightRequest = 377;
		this.leftmenuwidget1.Events = ((global::Gdk.EventMask)(256));
		this.leftmenuwidget1.Name = "leftmenuwidget1";
		this.hbox2.Add(this.leftmenuwidget1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.leftmenuwidget1]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vboxPage = new global::Gtk.VBox();
		this.vboxPage.Name = "vboxPage";
		this.vboxPage.Spacing = 6;
		// Container child vboxPage.Gtk.Box+BoxChild
		this.eventboxState = new global::Gtk.EventBox();
		this.eventboxState.Name = "eventboxState";
		// Container child eventboxState.Gtk.Container+ContainerChild
		this.labelState = new global::Gtk.Label();
		this.labelState.WidthRequest = 513;
		this.labelState.HeightRequest = 40;
		this.labelState.Name = "labelState";
		this.labelState.Xalign = 0F;
		this.labelState.Yalign = 0F;
		this.labelState.LabelProp = global::Mono.Unix.Catalog.GetString("DaaSXpert Client");
		this.eventboxState.Add(this.labelState);
		this.vboxPage.Add(this.eventboxState);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxPage[this.eventboxState]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.hbox2.Add(this.vboxPage);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vboxPage]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox3.Add(this.hbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.image28 = new global::Gtk.Image();
		this.image28.WidthRequest = 788;
		this.image28.HeightRequest = 79;
		this.image28.Name = "image28";
		this.image28.Xalign = 0F;
		this.image28.Yalign = 0F;
		this.image28.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("client.Resources.banner.png");
		this.vbox3.Add(this.image28);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image28]));
		w12.Position = 2;
		w12.Fill = false;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		//this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
