//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CLIENT_VERSION {
            get {
                return ResourceManager.GetString("CLIENT_VERSION", resourceCulture);
            }
        }
        
        internal static string MY_DEVICE_TYPE {
            get {
                return ResourceManager.GetString("MY_DEVICE_TYPE", resourceCulture);
            }
        }
        
        internal static string HCVK_HEADER_AUTH_TOKEN {
            get {
                return ResourceManager.GetString("HCVK_HEADER_AUTH_TOKEN", resourceCulture);
            }
        }
        
        internal static string HCVKA_REQUEST_CONNECT {
            get {
                return ResourceManager.GetString("HCVKA_REQUEST_CONNECT", resourceCulture);
            }
        }
        
        internal static string HCVKA_REQUEST_DISCONNECT {
            get {
                return ResourceManager.GetString("HCVKA_REQUEST_DISCONNECT", resourceCulture);
            }
        }
        
        internal static string HCVKA_REQUEST_HEARTBEAT {
            get {
                return ResourceManager.GetString("HCVKA_REQUEST_HEARTBEAT", resourceCulture);
            }
        }
        
        internal static string HCVKA_REQUEST_ONCONNECT {
            get {
                return ResourceManager.GetString("HCVKA_REQUEST_ONCONNECT", resourceCulture);
            }
        }
        
        internal static string HCVKA_REQUEST_RECONNECT {
            get {
                return ResourceManager.GetString("HCVKA_REQUEST_RECONNECT", resourceCulture);
            }
        }

		internal static string HCVKA_REQUEST_DEVICEATTACH {
			get {
				return ResourceManager.GetString ("HCVKA_REQUEST_DEVICEATTACH", resourceCulture);
			}
		}

		internal static string HCVKA_REQUEST_DEVICEDETACH {
			get {
				return ResourceManager.GetString ("HCVKA_REQUEST_DEVICEDETACH", resourceCulture);
			}
		}

		internal static string HCVKB_REQUEST_CHANGE_INFO {
            get {
                return ResourceManager.GetString("HCVKB_REQUEST_CHANGE_INFO", resourceCulture);
            }
        }

		internal static string HCVKB_REQUEST_PASSWORD_VALIDATE {
			get {
				return ResourceManager.GetString ("HCVKB_REQUEST_PASSWORD_VALIDATE", resourceCulture);
			}
		}

		internal static string HCVKB_REQUEST_CLEAR_SESSION {
            get {
                return ResourceManager.GetString("HCVKB_REQUEST_CLEAR_SESSION", resourceCulture);
            }
        }
        
        internal static string HCVKB_REQUEST_DESKTOP {
            get {
                return ResourceManager.GetString("HCVKB_REQUEST_DESKTOP", resourceCulture);
            }
        }
        
        internal static string HCVKB_REQUEST_DESKTOP_INFO {
            get {
                return ResourceManager.GetString("HCVKB_REQUEST_DESKTOP_INFO", resourceCulture);
            }
        }
        
        internal static string HCVKB_REQUEST_DESKTOP_POWER_CONTROL {
            get {
                return ResourceManager.GetString("HCVKB_REQUEST_DESKTOP_POWER_CONTROL", resourceCulture);
            }
        }
        
        internal static string HCVKB_REQUEST_LOGIN {
            get {
                return ResourceManager.GetString("HCVKB_REQUEST_LOGIN", resourceCulture);
            }
        }
        
        internal static string HCVKB_REQUEST_LOGOUT {
            get {
                return ResourceManager.GetString("HCVKB_REQUEST_LOGOUT", resourceCulture);
            }
        }
        
        internal static string HCVKB_REQUEST_POOL_INFO {
            get {
                return ResourceManager.GetString("HCVKB_REQUEST_POOL_INFO", resourceCulture);
            }
        }
        
        internal static string HCVKB_REQUEST_RECOMMEND_SERVER {
            get {
                return ResourceManager.GetString("HCVKB_REQUEST_RECOMMEND_SERVER", resourceCulture);
            }
        }
        
        internal static string HCVKB_REQUEST_TOKEN_REFRESH {
            get {
                return ResourceManager.GetString("HCVKB_REQUEST_TOKEN_REFRESH", resourceCulture);
            }
        }
        
        internal static string HCVKL_REQUEST_LOG_REPORT {
            get {
                return ResourceManager.GetString("HCVKL_REQUEST_LOG_REPORT", resourceCulture);
            }
        }
        
        internal static string REQUEST_NODE_NAME {
            get {
                return ResourceManager.GetString("REQUEST_NODE_NAME", resourceCulture);
            }
        }
        
        internal static string TYPE_INFO_TYPE_CONNECTION {
            get {
                return ResourceManager.GetString("TYPE_INFO_TYPE_CONNECTION", resourceCulture);
            }
        }
        
        internal static string TYPE_INFO_TYPE_INFO {
            get {
                return ResourceManager.GetString("TYPE_INFO_TYPE_INFO", resourceCulture);
            }
        }
        
        internal static string TYPE_ACCESS_DIV_DEDICATED {
            get {
                return ResourceManager.GetString("TYPE_ACCESS_DIV_DEDICATED", resourceCulture);
            }
        }
        
        internal static string TYPE_ACCESS_DIV_SHARED {
            get {
                return ResourceManager.GetString("TYPE_ACCESS_DIV_SHARED", resourceCulture);
            }
        }
        
        internal static string LOG_CL_DESKTOPINFO_POOL {
            get {
                return ResourceManager.GetString("LOG_CL_DESKTOPINFO_POOL", resourceCulture);
            }
        }
        
        internal static string LOG_CL_DESKTOPINFO_POWER {
            get {
                return ResourceManager.GetString("LOG_CL_DESKTOPINFO_POWER", resourceCulture);
            }
        }
        
        internal static string LOG_CL_DESKTOPINFO_STATUS {
            get {
                return ResourceManager.GetString("LOG_CL_DESKTOPINFO_STATUS", resourceCulture);
            }
        }
        
        internal static string LOG_CL_DESKTOP_CONNECT {
            get {
                return ResourceManager.GetString("LOG_CL_DESKTOP_CONNECT", resourceCulture);
            }
        }
        
        internal static string LOG_CL_DESKTOP_CONNECTIONINFO {
            get {
                return ResourceManager.GetString("LOG_CL_DESKTOP_CONNECTIONINFO", resourceCulture);
            }
        }
        
        internal static string LOG_CL_DESKTOP_DISCONNECT {
            get {
                return ResourceManager.GetString("LOG_CL_DESKTOP_DISCONNECT", resourceCulture);
            }
        }
        
        internal static string LOG_CL_DESKTOP_ONCONNECT {
            get {
                return ResourceManager.GetString("LOG_CL_DESKTOP_ONCONNECT", resourceCulture);
            }
        }
        
        internal static string LOG_CL_DESKTOP_RECONNECT {
            get {
                return ResourceManager.GetString("LOG_CL_DESKTOP_RECONNECT", resourceCulture);
            }
        }
        
        internal static string LOG_CL_USER_CHANGEINFO {
            get {
                return ResourceManager.GetString("LOG_CL_USER_CHANGEINFO", resourceCulture);
            }
        }
        
        internal static string LOG_CL_USER_INTEGRITY {
            get {
                return ResourceManager.GetString("LOG_CL_USER_INTEGRITY", resourceCulture);
            }
        }
        
        internal static string LOG_CL_USER_LOGIN {
            get {
                return ResourceManager.GetString("LOG_CL_USER_LOGIN", resourceCulture);
            }
        }
        
        internal static string LOG_CL_USER_LOGOUT {
            get {
                return ResourceManager.GetString("LOG_CL_USER_LOGOUT", resourceCulture);
            }
        }

		internal static string HCVKB_REQUEST_SYSTEM_PUBLICKEY {
			get {
				return ResourceManager.GetString ("HCVKB_REQUEST_SYSTEM_PUBLICKEY", resourceCulture);
			}
		}

	}
}
