#!/bin/bash

## simple debian10 preinstall for monodevelop 

#sudo apt install apt-transport-https dirmngr
#sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
#echo "deb https://download.mono-project.com/repo/debian vs-buster main" | sudo tee /etc/apt/sources.list.d/mono-official-vs.list
#sudo apt update

#exit 0

PID=$(ps -eaf | grep client.exe | grep -v grep | awk '{print $2}')
if [ "$PID" = "" ];then
  echo "client.exe does not exist, exiting.."
  exit 0
else
  echo "PID = $PID"
fi

for p in $PID
do
 echo "Process $p is running"
 echo "killing $PID"
 kill  $p
done
echo "Finish Kill Process!!"
