//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCVK.HCVKAService.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HCVKAService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EVENT_LOG_NAME {
            get {
                return ResourceManager.GetString("EVENT_LOG_NAME", resourceCulture);
            }
        }
        
        internal static string EXECUTE_NAME_FOR_HCVKASERVICE {
            get {
                return ResourceManager.GetString("EXECUTE_NAME_FOR_HCVKASERVICE", resourceCulture);
            }
        }
        
        internal static string EXECUTE_NAME_FOR_HCVKATRAY {
            get {
                return ResourceManager.GetString("EXECUTE_NAME_FOR_HCVKATRAY", resourceCulture);
            }
        }
        
        internal static string EXECUTE_NAME_FOR_HCVKSLIBRARY {
            get {
                return ResourceManager.GetString("EXECUTE_NAME_FOR_HCVKSLIBRARY", resourceCulture);
            }
        }
        
        internal static string FW_GROUP_ENAME {
            get {
                return ResourceManager.GetString("FW_GROUP_ENAME", resourceCulture);
            }
        }
        
        internal static string FW_RULE_NAME_INTERFACE {
            get {
                return ResourceManager.GetString("FW_RULE_NAME_INTERFACE", resourceCulture);
            }
        }
        
        internal static string FW_RULE_NAME_TEST_INTERFACE {
            get {
                return ResourceManager.GetString("FW_RULE_NAME_TEST_INTERFACE", resourceCulture);
            }
        }
        
        internal static string FW_RULE_NAME_VDI {
            get {
                return ResourceManager.GetString("FW_RULE_NAME_VDI", resourceCulture);
            }
        }
        
        internal static string HCVKB_REQUEST_HEALTH_REPORT {
            get {
                return ResourceManager.GetString("HCVKB_REQUEST_HEALTH_REPORT", resourceCulture);
            }
        }
        
        internal static string HCVKB_REQUEST_LOG_REPORT {
            get {
                return ResourceManager.GetString("HCVKB_REQUEST_LOG_REPORT", resourceCulture);
            }
        }
        
        internal static string HCVKB_REQUEST_RE_REGISTRATION {
            get {
                return ResourceManager.GetString("HCVKB_REQUEST_RE_REGISTRATION", resourceCulture);
            }
        }
        
        internal static string HCVK_HEADER_AUTH_TOKEN {
            get {
                return ResourceManager.GetString("HCVK_HEADER_AUTH_TOKEN", resourceCulture);
            }
        }
        
        internal static string IPC_SERVER_NAME {
            get {
                return ResourceManager.GetString("IPC_SERVER_NAME", resourceCulture);
            }
        }
        
        internal static string LOG_AG_COMMON_INTEGRITY {
            get {
                return ResourceManager.GetString("LOG_AG_COMMON_INTEGRITY", resourceCulture);
            }
        }
        
        internal static string LOG_AG_COMMON_REGISTRATION {
            get {
                return ResourceManager.GetString("LOG_AG_COMMON_REGISTRATION", resourceCulture);
            }
        }
        
        internal static string LOG_AG_COMMON_REREGISTRATION {
            get {
                return ResourceManager.GetString("LOG_AG_COMMON_REREGISTRATION", resourceCulture);
            }
        }
        
        internal static string LOG_AG_DESKTOP_CONNECT {
            get {
                return ResourceManager.GetString("LOG_AG_DESKTOP_CONNECT", resourceCulture);
            }
        }
        
        internal static string LOG_AG_DESKTOP_DISCONNECT {
            get {
                return ResourceManager.GetString("LOG_AG_DESKTOP_DISCONNECT", resourceCulture);
            }
        }
        
        internal static string LOG_AG_DESKTOP_ONCONNECT {
            get {
                return ResourceManager.GetString("LOG_AG_DESKTOP_ONCONNECT", resourceCulture);
            }
        }
        
        internal static string LOG_AG_DESKTOP_RECONNECT {
            get {
                return ResourceManager.GetString("LOG_AG_DESKTOP_RECONNECT", resourceCulture);
            }
        }
        
        internal static string LOG_A_0001 {
            get {
                return ResourceManager.GetString("LOG_A_0001", resourceCulture);
            }
        }
        
        internal static string LOG_A_0002 {
            get {
                return ResourceManager.GetString("LOG_A_0002", resourceCulture);
            }
        }
        
        internal static string LOG_A_0003 {
            get {
                return ResourceManager.GetString("LOG_A_0003", resourceCulture);
            }
        }
        
        internal static string LOG_A_0004 {
            get {
                return ResourceManager.GetString("LOG_A_0004", resourceCulture);
            }
        }
        
        internal static string LOG_A_0005 {
            get {
                return ResourceManager.GetString("LOG_A_0005", resourceCulture);
            }
        }
        
        internal static string LOG_A_0006 {
            get {
                return ResourceManager.GetString("LOG_A_0006", resourceCulture);
            }
        }
        
        internal static string NODE_NAME_HCVKB {
            get {
                return ResourceManager.GetString("NODE_NAME_HCVKB", resourceCulture);
            }
        }
        
        internal static string NODE_NAME_HCVKC {
            get {
                return ResourceManager.GetString("NODE_NAME_HCVKC", resourceCulture);
            }
        }
        
        internal static string NODE_VERSION_MIN_HCVKB {
            get {
                return ResourceManager.GetString("NODE_VERSION_MIN_HCVKB", resourceCulture);
            }
        }
        
        internal static string NODE_VERSION_MIN_HCVKC {
            get {
                return ResourceManager.GetString("NODE_VERSION_MIN_HCVKC", resourceCulture);
            }
        }
        
        internal static string PROCESS_NAME_FOR_HCVKATRAY {
            get {
                return ResourceManager.GetString("PROCESS_NAME_FOR_HCVKATRAY", resourceCulture);
            }
        }
        
        internal static string REG_RDP_PORT_SUBKEY {
            get {
                return ResourceManager.GetString("REG_RDP_PORT_SUBKEY", resourceCulture);
            }
        }
        
        internal static string REG_RDP_SUBKEY {
            get {
                return ResourceManager.GetString("REG_RDP_SUBKEY", resourceCulture);
            }
        }
        
        internal static string REQUEST_NODE_NAME {
            get {
                return ResourceManager.GetString("REQUEST_NODE_NAME", resourceCulture);
            }
        }
        
        internal static string WINDOWS_RDP_SERVICE_NAME {
            get {
                return ResourceManager.GetString("WINDOWS_RDP_SERVICE_NAME", resourceCulture);
            }
        }
        
        internal static string WINDOWS_SESSION_RDP_SERVICE_NAME {
            get {
                return ResourceManager.GetString("WINDOWS_SESSION_RDP_SERVICE_NAME", resourceCulture);
            }
        }
        
        internal static string WINDOWS_USER_MODE_RDP_SERVICE_NAME {
            get {
                return ResourceManager.GetString("WINDOWS_USER_MODE_RDP_SERVICE_NAME", resourceCulture);
            }
        }
    }
}
